- name: install the vagrant rpm package
  dnf:
    name: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.rpm
    state: present
  when: "'{{ ansible_distribution|lower }}' == 'fedora'"
