- name: accept docker gpg key
  rpm_key:
    state: present
    key: https://yum.dockerproject.org/gpg

- block:
  - name: add docker-engine yum repository
    get_url:
      url: https://docs.docker.com/engine/installation/linux/repo_files/fedora/docker.repo
      dest: /etc/yum.repos.d/docker.repo
      mode: 0644

  - name: install docker-engine
    dnf:
      name: docker-engine
      state: present

  - name: add user to docker group
    user:
      name: dl
      groups: docker
      append: yes

  - name: enable docker-engine service
    service:
      name: docker
      state: started
  when: "'{{ ansible_distribution|lower }}' == 'fedora'"
