- rpm_key:
    state: present
    key: https://www.virtualbox.org/download/oracle_vbox.asc

- block:
  - name: add VirtualBox repository
    get_url:
      url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
      dest: /etc/yum.repos.d/virtualbox.repo
      mode: 0644

  - name: install the dkms package
    dnf:
      name: dkms
      state: present

  - name: install the VirtualBox rpm package
    dnf:
      name: VirtualBox-5.1
      state: present
  when: "'{{ ansible_distribution|lower }}' == 'fedora'"
